version: "3.7"

services:
    # imagem micro-auth
    micro_auth:
        build:
            args:
                user: laravel
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - redis
            - queue
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - microservices_auth

    # queue
    queue:
        build:
            args:
                user: laravel
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        command: 'php artisan queue:work'
        restart: unless-stopped
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - microservices_auth

    #nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8006:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - microservices_auth
        extra_hosts:
            - "host.docker.internal:host-gateway"

    # database
    db-micro-auth:
        image: mariadb
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - 3308:3306
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        networks:
            - microservices_auth

    # redis
    redis:
        image: redis:latest
        restart: unless-stopped
        networks:
            - microservices_auth

networks:
    microservices_auth:
        driver: bridge
